// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeGROLAmnCbuRFfphSDmvnXK9UxtydGVU',
    appId: '1:311723193427:web:99dc71118faa933167c2a6',
    messagingSenderId: '311723193427',
    projectId: 'jaden-proj2',
    authDomain: 'jaden-proj2.firebaseapp.com',
    storageBucket: 'jaden-proj2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf-SNgP7FAzUvFhGHVLsJyxIuWu6FKEMg',
    appId: '1:311723193427:android:4567e8a227207fbc67c2a6',
    messagingSenderId: '311723193427',
    projectId: 'jaden-proj2',
    storageBucket: 'jaden-proj2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR240tVVdszNaTNFe6nZXiOc5u-PkDafI',
    appId: '1:311723193427:ios:b33879be9a21f03667c2a6',
    messagingSenderId: '311723193427',
    projectId: 'jaden-proj2',
    storageBucket: 'jaden-proj2.firebasestorage.app',
    iosBundleId: 'com.example.proj2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR240tVVdszNaTNFe6nZXiOc5u-PkDafI',
    appId: '1:311723193427:ios:b33879be9a21f03667c2a6',
    messagingSenderId: '311723193427',
    projectId: 'jaden-proj2',
    storageBucket: 'jaden-proj2.firebasestorage.app',
    iosBundleId: 'com.example.proj2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeGROLAmnCbuRFfphSDmvnXK9UxtydGVU',
    appId: '1:311723193427:web:50a259a484f69f7867c2a6',
    messagingSenderId: '311723193427',
    projectId: 'jaden-proj2',
    authDomain: 'jaden-proj2.firebaseapp.com',
    storageBucket: 'jaden-proj2.firebasestorage.app',
  );
}
